spring:
  application:
    name: creditcard
  datasource:
    url: jdbc:mysql://creditcard-db-1-mysql/creditcard?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    password: 1234qwer
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update